### ISSUE TITLE
Спасите

### ISSUE THREAD

**Issue by ioioihhh** [FSystem88/spymer#11]
СПАСИТЕ ОН ДО СИХ ПОР СПАМИТ!!!!

**Comment by mishailovic** [comment]
@ioioihhh Какая ось? После остановки проги сообщения могут идти около 1~2 часов из-за задержки сервисов, такое может быть. Для перестраховки можешь перезагрузить телефон или компьютер на котором запущен спамер.

**Comment by ioioihhh** [comment]
Спасибо


сб, 9 мая 2020 г., 13:51 Mikhail Kuznetsov <notifications@github.com>:

**Comment by mishailovic** [comment]
Спасибо будешь говорить когда спам действительно остановится, если проблема
решена, закрывай иссью.

сб, 9 мая 2020 г., 13:53 ioioihhh <notifications@github.com>:

> Спасибо
>
>
> сб, 9 мая 2020 г., 13:51 Mikhail Kuznetsov <notifications@github.com>:
>
>
