### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by DOnilist** [FSystem88/spymer#17]
Как обновить?

**Comment by DOnilist** [comment]
![06A151D6-D1B2-48C9-B018-EA766976A399](https://user-images.githubusercontent.com/67166151/85394794-c7609800-b557-11ea-93b4-a50ef9394ad0.png)

**Comment by FSystem88** [comment]
<code>cd ~/spymer</code><br>
<code>git pull</code><br>
<code>sh install.sh</code><br>
