### ISSUE TITLE
If post request fails increment will not be executed and while is infinitive

### ISSUE THREAD

**Issue by vmred** [FSystem88/spymer#2]
In while loop increment executes only if all post requests are successful. If any failed, increment will not be executed it's going to infinite loop.

**Comment by Tufuteca** [comment]
Hello, I was faced with the fact that termux crashed and now the script is turned on at random times, how can this be fixed? (Can you continue the conversation in Russian?)

**Comment by FSystem88** [comment]
@vmred можно и на русском.
