### ISSUE TITLE
Why this is so shitable project?

### ISSUE THREAD

**Issue by r0tt3n-m3m0ry** [FSystem88/spymer#23]
Вот разработкой того проекта занимаются три более-менее шарящих парней, и вот им я и хочу задать вопрос: доколе будет столько говнокода?

**Comment by mishailovic** [comment]
> Вот разработкой того проекта занимаются три более-менее шарящих парней, и вот им я и хочу задать вопрос: доколе будет столько говнокода?

Это не говнокод, а уникальный стиль автора, если есть идеи или что-то вроде того, велком, кидай пул реквест и Ваня его рассмотрит.
