### ISSUE TITLE
Проблема с SSL

### ISSUE THREAD

**Issue by fellowmean5** [FSystem88/spymer#27]
Не могу запустить спаммер,вот скриншот проблемы 
![image](https://user-images.githubusercontent.com/73715753/97742538-16fa3600-1aed-11eb-86fb-45fd60029557.png)

**Comment by Rac1z** [comment]
тоже самое

**Comment by fellowmean5** [comment]
Кста,у меня только работает яндекс еда.Можно ли как то сделать,чтобы каждую секунду отправлялось смс только от яндекс еды,а то интервал огромный

**Comment by FSystem88** [comment]
> Не могу запустить спаммер,вот скриншот проблемы
> ![image](https://user-images.githubusercontent.com/73715753/97742538-16fa3600-1aed-11eb-86fb-45fd60029557.png)


> тоже самое

ваш ip адрес заблокирован, скорее всего из-за дудоса на мой сайт...

**Comment by FSystem88** [comment]
по всем вопросам писать в телеграмм t.me/FSystem88
