### ISSUE TITLE
I have error what i can do?

### ISSUE THREAD

**Issue by sanscross** [FSystem88/spymer#33]
ERROR: Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/spymer", line 1058, in <module>
    MAIN()
  File "/data/data/com.termux/files/usr/bin/spymer", line 1049, in MAIN
    Main()                                                                                File "/data/data/com.termux/files/usr/bin/spymer", line 1048, in Main
    main()                                                                                File "/data/data/com.termux/files/usr/bin/spymer", line 992, in main
    checkver()                                                                            File "/data/data/com.termux/files/usr/bin/spymer", line 681, in checkver
    version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json                                                                          return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)                                                     File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode                                                                                         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by FSystem88** [comment]
Походу твой ip в бане, я себе жёсткие ограничения на сайте поставил, от ддоса. Напиши свой АЙПИ

**Comment by sanscross** [comment]
> Походу твой ip в бане, я себе жёсткие ограничения на сайте поставил, от ддоса. Напиши свой АЙПИ

can i sand it on your email ?

**Comment by sanscross** [comment]
> > Походу твой ip в бане, я себе жёсткие ограничения на сайте поставил, от ддоса. Напиши свой АЙПИ
> 
> могу я отшлифовать это по электронной почте?

And how much sessions with spymer i can start
Becose i start 30 sesions with spymer on kali linuks

**Comment by FSystem88** [comment]
напиши мне в телеграмме https://t.me/FSystem88
