### ISSUE TITLE
Как установить на айфоне с джейлбрейк?

### ISSUE THREAD

**Issue by ScrubHax0r** [FSystem88/spymer#38]
Здравствуйте, дает ошибку если пытаюсь установить через терминал на айос. 
![ADC079E0-A425-43C3-A137-A7F4F4DDEB50](https://user-images.githubusercontent.com/66184829/107319955-d6796380-6ab0-11eb-98df-d63e5cb5e495.png)

**Comment by s0563858** [comment]
нужно установить python3 и pip3 - для начала проверьте работает ли в вашем терминале команда apt-get  если да то пробейте:
apt-get install python3

**Comment by FSystem88** [comment]
к сожалению не могу сказать точно, так как в ios отличается внутренняя файловая система от привычного линукса

**Comment by mishailovic** [comment]
Поддержка айоси уже давным давно сломана, лучше даже не пытаться. Но можно попробовать установить без скриптов, клонироя репозиторий и запуская вручную. В альпайне пакеты называются py3 и py3-pip
