### ISSUE TITLE
не скачался пайтон

### ISSUE THREAD

**Issue by ferrariwest420** [FSystem88/spymer#59]
![FE3300B7-2061-4A1E-8B6D-0A0B671926E6](https://user-images.githubusercontent.com/106780379/192088988-52738368-f435-45ac-a863-9a33c7b1dbac.png)

**Comment by ferrariwest420** [comment]
![Uploading 1495400F-5360-4392-9B48-C384097ADECE.png…]()

**Comment by ferrariwest420** [comment]
![9E55FBE2-3823-45FF-A5F2-28FDFDE9EC9E](https://user-images.githubusercontent.com/106780379/192089150-7d9143e8-bcf7-42ac-b0d6-89297e6f659a.png)

**Comment by FSystem88** [comment]
> ![9E55FBE2-3823-45FF-A5F2-28FDFDE9EC9E](https://user-images.githubusercontent.com/106780379/192089150-7d9143e8-bcf7-42ac-b0d6-89297e6f659a.png)

а вас не смущает , что проект закрыт?
