### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by livxbox5** [FSystem88/spymer#61]
remove please #61

**Comment by Dennis1678** [comment]
Тоже самое, на сколько я понял, это не решаемо

**Comment by livxbox5** [comment]
> Тоже самое, на сколько я понял, это не решаемо
а разраб жив или нет?

**Comment by Anton064** [comment]
Я не розраб но могу попробовать решить, если это так сильно нужно

пт, 17 нояб. 2023 г., 12:07 livxbox5 ***@***.***>:

**Comment by FSystem88** [comment]
> > Тоже самое, на сколько я понял, это не решаемо
> > а разраб жив или нет?

разраб жив, в вот спаммер уже как 3 года не жив, НАПИСАНО ЖЕ БЛЯТЬ НА ГЛАВНОЙ СТРАНИЦЕ, ХВАТИТ ДОЛБИТЬСЯ В ГЛАЗА !!!
